env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  require-jsdoc: off
  react/react-in-jsx-scope: off
  max-len:
  - error
  - code: 120
    ignoreComments: true
    ignoreTrailingComments: true
    ignoreUrls: true
    ignoreStrings: true 
    ignoreTemplateLiterals: true 
